version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - sudo yum install -y yum-utils shadow-utils; sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo; sudo yum -y install terraform
      - terraform version
  pre_build:
    commands:
      - echo Initializing Terraform...
      - make init
  build:
    commands:
      - echo Planning Terraform...
      - make plan -var 'cluster-name=codepipeline-01'
      - echo Applying Terraform...
      - make apply
      - echo Applying Kubernetes manifests...
      - aws eks update-kubeconfig --name <your-cluster-name> --region <your-region>
      - make k8s-apply
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
